apiVersion: v1
data:
  _example: |-
    ################################
    #                              #
    #    EXAMPLE CONFIGURATION     #
    #                              #
    ################################

    # This block is not actually functional configuration,
    # but serves to illustrate the available configuration
    # options and document them in a way that is accessible
    # to users that `kubectl edit` this config map.
    #
    # These sample configuration options may be copied out of
    # this example block and unindented to be in the data block
    # to actually change the configuration.

    # List of repositories for which tag to digest resolving should be skipped
    registries-skipping-tag-resolving: "kind.local,ko.local,dev.local"

    # Maximum time allowed for an image's digests to be resolved.
    digest-resolution-timeout: "10s"

    # Duration we wait for the deployment to be ready before considering it failed.
    progress-deadline: "600s"

    # Sets the queue proxy's CPU request.
    # If omitted, a default value (currently "25m"), is used.
    queue-sidecar-cpu-request: "25m"

    # Sets the queue proxy's CPU limit.
    # If omitted, a default value (currently "1000m"), is used when
    # `queueproxy.resource-defaults` is set to `Enabled`.
    queue-sidecar-cpu-limit: "1000m"

    # Sets the queue proxy's memory request.
    # If omitted, a default value (currently "400Mi"), is used when
    # `queueproxy.resource-defaults` is set to `Enabled`.
    queue-sidecar-memory-request: "400Mi"

    # Sets the queue proxy's memory limit.
    # If omitted, a default value (currently "800Mi"), is used when
    # `queueproxy.resource-defaults` is set to `Enabled`.
    queue-sidecar-memory-limit: "800Mi"

    # Sets the queue proxy's ephemeral storage request.
    # If omitted, no value is specified and the system default is used.
    queue-sidecar-ephemeral-storage-request: "512Mi"

    # Sets the queue proxy's ephemeral storage limit.
    # If omitted, no value is specified and the system default is used.
    queue-sidecar-ephemeral-storage-limit: "1024Mi"

    # Sets tokens associated with specific audiences for queue proxy - used by QPOptions
    #
    # For example, to add the `service-x` audience:
    #    queue-sidecar-token-audiences: "service-x"
    # Also supports a list of audiences, for example:
    #    queue-sidecar-token-audiences: "service-x,service-y"
    # If omitted, or empty, no tokens are created
    queue-sidecar-token-audiences: ""

    # Sets rootCA for the queue proxy - used by QPOptions
    # If omitted, or empty, no rootCA is added to the golang rootCAs
    queue-sidecar-rootca: ""

    # If set, it automatically configures pod anti-affinity requirements for all Knative services.
    # It employs the `preferredDuringSchedulingIgnoredDuringExecution` weighted pod affinity term,
    # aligning with the Knative revision label. It yields the configuration below in all workloads' deployments:
    # `
    #   affinity:
    #     podAntiAffinity:
    #       preferredDuringSchedulingIgnoredDuringExecution:
    #       - podAffinityTerm:
    #           topologyKey: kubernetes.io/hostname
    #           labelSelector:
    #             matchLabels:
    #               serving.knative.dev/revision: {{revision-name}}
    #         weight: 100
    # `
    # This may be "none" or "prefer-spread-revision-over-nodes" (default)
    # default-affinity-type: "prefer-spread-revision-over-nodes"

    # runtime-class-name contains the selector for which runtimeClassName
    # is selected to put in a revision.
    # By default, it is not set by Knative.
    #
    # Example:
    # runtime-class-name: |
    #   "":
    #     selector:
    #       use-default-runc: "yes"
    #   kata: {}
    #   gvisor:
    #     selector:
    #       use-gvisor: "please"
    runtime-class-name: ""
  queue-sidecar-image: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:56142833a9f87213e055045f0ea59c3f00f024d095c052f7669f7b9d77c55e54
kind: ConfigMap
metadata:
  annotations:
    knative.dev/example-checksum: 720ddb97
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"_example":"################################\n#                              #\n#    EXAMPLE CONFIGURATION     #\n#                              #\n################################\n\n# This block is not actually functional configuration,\n# but serves to illustrate the available configuration\n# options and document them in a way that is accessible\n# to users that `kubectl edit` this config map.\n#\n# These sample configuration options may be copied out of\n# this example block and unindented to be in the data block\n# to actually change the configuration.\n\n# List of repositories for which tag to digest resolving should be skipped\nregistries-skipping-tag-resolving: \"kind.local,ko.local,dev.local\"\n\n# Maximum time allowed for an image's digests to be resolved.\ndigest-resolution-timeout: \"10s\"\n\n# Duration we wait for the deployment to be ready before considering it failed.\nprogress-deadline: \"600s\"\n\n# Sets the queue proxy's CPU request.\n# If omitted, a default value (currently \"25m\"), is used.\nqueue-sidecar-cpu-request: \"25m\"\n\n# Sets the queue proxy's CPU limit.\n# If omitted, a default value (currently \"1000m\"), is used when\n# `queueproxy.resource-defaults` is set to `Enabled`.\nqueue-sidecar-cpu-limit: \"1000m\"\n\n# Sets the queue proxy's memory request.\n# If omitted, a default value (currently \"400Mi\"), is used when\n# `queueproxy.resource-defaults` is set to `Enabled`.\nqueue-sidecar-memory-request: \"400Mi\"\n\n# Sets the queue proxy's memory limit.\n# If omitted, a default value (currently \"800Mi\"), is used when\n# `queueproxy.resource-defaults` is set to `Enabled`.\nqueue-sidecar-memory-limit: \"800Mi\"\n\n# Sets the queue proxy's ephemeral storage request.\n# If omitted, no value is specified and the system default is used.\nqueue-sidecar-ephemeral-storage-request: \"512Mi\"\n\n# Sets the queue proxy's ephemeral storage limit.\n# If omitted, no value is specified and the system default is used.\nqueue-sidecar-ephemeral-storage-limit: \"1024Mi\"\n\n# Sets tokens associated with specific audiences for queue proxy - used by QPOptions\n#\n# For example, to add the `service-x` audience:\n#    queue-sidecar-token-audiences: \"service-x\"\n# Also supports a list of audiences, for example:\n#    queue-sidecar-token-audiences: \"service-x,service-y\"\n# If omitted, or empty, no tokens are created\nqueue-sidecar-token-audiences: \"\"\n\n# Sets rootCA for the queue proxy - used by QPOptions\n# If omitted, or empty, no rootCA is added to the golang rootCAs\nqueue-sidecar-rootca: \"\"\n\n# If set, it automatically configures pod anti-affinity requirements for all Knative services.\n# It employs the `preferredDuringSchedulingIgnoredDuringExecution` weighted pod affinity term,\n# aligning with the Knative revision label. It yields the configuration below in all workloads' deployments:\n# `\n#   affinity:\n#     podAntiAffinity:\n#       preferredDuringSchedulingIgnoredDuringExecution:\n#       - podAffinityTerm:\n#           topologyKey: kubernetes.io/hostname\n#           labelSelector:\n#             matchLabels:\n#               serving.knative.dev/revision: {{revision-name}}\n#         weight: 100\n# `\n# This may be \"none\" or \"prefer-spread-revision-over-nodes\" (default)\n# default-affinity-type: \"prefer-spread-revision-over-nodes\"\n\n# runtime-class-name contains the selector for which runtimeClassName\n# is selected to put in a revision.\n# By default, it is not set by Knative.\n#\n# Example:\n# runtime-class-name: |\n#   \"\":\n#     selector:\n#       use-default-runc: \"yes\"\n#   kata: {}\n#   gvisor:\n#     selector:\n#       use-gvisor: \"please\"\nruntime-class-name: \"\"","queue-sidecar-image":"gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:56142833a9f87213e055045f0ea59c3f00f024d095c052f7669f7b9d77c55e54"},"kind":"ConfigMap","metadata":{"annotations":{"knative.dev/example-checksum":"720ddb97"},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"knative-serving","app.kubernetes.io/version":"1.15.2"},"name":"config-deployment","namespace":"knative-serving","ownerReferences":[{"apiVersion":"operator.knative.dev/v1beta1","blockOwnerDeletion":true,"controller":true,"kind":"KnativeServing","name":"knative-serving","uid":"087e120e-25fa-4fad-9ed2-22ac5f6a88a4"}]}}
    manifestival: new
  creationTimestamp: "2024-09-23T19:34:03Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.15.2
  name: config-deployment
  namespace: knative-serving
  ownerReferences:
  - apiVersion: operator.knative.dev/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: KnativeServing
    name: knative-serving
    uid: 087e120e-25fa-4fad-9ed2-22ac5f6a88a4
  resourceVersion: "370965"
  uid: 962b8970-e557-42e1-8cde-884fdfb9cb4a
