apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: graphql
  namespace: kn-poc-services
spec:
  template:
    spec:
      containers:
        - image: dev.local/kn-graphql:v1
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "test"
            - name: "GRPC_SERVICE"
              value: "grpc-ping.kn-poc-services.svc.cluster.local"
            - name: GRPC_PORT
              value: "80"
